### ISSUE TITLE
Try and except are both getting implemented, check 

### ISSUE THREAD

**Issue by vamshiballikonda** [abhiroyg/islanddetection#3]
The file island2.py will work well, but the line 102 is called even though its not required. But the answers are correct.
Also it is to be noted that the first matched is gen to max load, the reverse is being implemented in the first step. There while sort, sort=reverse has to be done. Then I guess it will work perfect.

**Comment by abhiroyg** [comment]
Yeah line 102 is not required.....but I wrote it such that, it stays consistent with `islands` list. Like if we want to use `bases` matrix, you get the same answer that of if you use `islands`.

**Comment by abhiroyg** [comment]
Just noticed that `sorted_generators` is not printing sorted order of generator indices. Will fix it.
